### ISSUE TITLE
Ability to add/update/delete/query the Keychain Items from Keychain

### ISSUE THREAD

**Issue by phongddo** [phongddo/SecureKey#5]
**Is your feature request related to a problem? Please describe.**
The framework should expose the public methods so they can manipulate the Keychain Items easily:
- [ ] Add the item to Keychain 
- [ ] Update the item persisted in Keychain based on its identifier
- [ ] Delete the item from Keychain based on its identifier
- [ ] Query the item from Keychain based on its identifier

**Describe the solution you'd like**
Wrap the methods exposed by KeychainServices:
- [Add the Keychain Item](https://developer.apple.com/documentation/security/1401659-secitemadd)
- [Update the Keychain Item](https://developer.apple.com/documentation/security/1393617-secitemupdate)
- [Delete the Keychain Item](https://developer.apple.com/documentation/security/1395547-secitemdelete)
- [Query the Keychain Item](https://developer.apple.com/documentation/security/1398306-secitemcopymatching)

**Requirements**
- For adding the item, the API should add the generic password only, i.e., [kSecClassGenericPassword](https://developer.apple.com/documentation/security/ksecclassgenericpassword).
- For adding/updating the item, the API should persist the `String` data only.
- For any item, it should be uniquely identified by a key only, so the key can be used to query when matching the item within the Keychain data store.

**Describe alternatives you've considered**
None

**Additional context**
None
